services:
  landing:
    image: nginx:alpine
    container_name: landing
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /opt/planopratico/landing:/var/www/landing:ro
    networks:
      - planopratico_net

networks:
  planopratico_net:
    external: true
