services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    env_file:
      - .env
    environment:
      - N8N_HOST=n8n.planopratico.shop
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - WEBHOOK_URL=https://n8n.planopratico.shop/
      - GENERIC_TIMEZONE=America/Sao_Paulo
      - TZ=America/Sao_Paulo
      - N8N_BLOCK_ENV_ACCESS_IN_NODE=false
      - WA_PHONE_NUMBER_ID=1289596924230439
    volumes:
      - /opt/planopratico/volumes/n8n_data:/home/node/.n8n
    networks:
      - planopratico_net

networks:
  planopratico_net:
    external: true
